### ISSUE TITLE
How to change palette in [params.theme] in config.toml

### ISSUE THREAD

**Issue by rio-codes** [joeroe/risotto#31]
Hello,

I was wondering if it was possible to change the palette? In your example site you have 
```
[params.theme]
palette = "gruvbox-dark"
``` 
which I found in static/css/colour. I see a lot of different colors listed in that file, but I'm not sure where to put the values. Where do I change which colors are used? Are there other palettes available?

Thank you!

**Comment by rio-codes** [comment]
I tinkered with this a bit and I understand how to tweak the colors now. I'm going to close this, sorry! This is a beautiful theme, thank you for making it.

**Comment by joeroe** [comment]
Currently there are only two palettes, gruvbox-dark and gruvbox-light (because I love gruvbox), by the plan is to add other popular terminal colour schemes.

Any PRs with more palettes would be much appreciated.
