### ISSUE TITLE
Trying to apply multi languages getting strange behaviour

### ISSUE THREAD

**Issue by Alexsandr0x** [joeroe/risotto#44]
So, I was trying to setup a simple blog using Hugo + Risotto with multi language english + portuguese, but then I notice that was already a template on risotto for that and it was a weird text on the available languages iteration.

The strange code is this one is on line 13~26 in [partials/lang.html](https://github.com/joeroe/risotto/blob/main/layouts/partials/lang.html#L13):

```
    {{ range .Page.AllTranslations }}
      {{ $translation := .}}
      {{ range $siteLanguages }}
          {{ if eq $translation.Lang .Lang }}
            {{ $selected := false }}
            {{ if eq $pageLang .Lang }}
                <br/><span class="active">$ echo $LANG<br/><b>{{ .LanguageName }}</b></span><br/>

            {{ else }}
                <br/><a href="{{ $translation.Permalink }}">export LANG={{ .LanguageName }}; ./{{ $pageName }}</a><br/>
            {{ end }}
          {{ end }}
      {{ end }}
    {{ end }}
```

I'm super newbie on this kind of stuff and IDK if '$ echo $LANG' is here to do something special but in my case just show as is:

![image](https://user-images.githubusercontent.com/8901883/209759293-8bd54b5f-0e7c-4b44-864a-8c3dd50039d8.png)

**Comment by joeroe** [comment]
This was contributed by @bedefaced in #25. It's just for decoration – [bash](https://en.wikipedia.org/wiki/Bash_(Unix_shell)) pseudocode that basically says "the current language is English; click here to see the About page in Portuguese".

I'd be open to a pull request with an alternative way of displaying the current and available languages of a page. I do agree that this one goes a bit too far with the terminal analogy. But I don't use multilingual mode so it hasn't been a priority for me so far.

**Comment by Alexsandr0x** [comment]
oh! okay! now I get it was a stylish thing.

So if it was suppose to emulate a terminal I wrongly thought that was a typo or a forgotten code for some reason.

IDK if others use the multilingual mode, I changed myself in my personal project cause I prefer something simplier.

Since is not a bug I will close this issue.

**Comment by alankritjoshi** [comment]
@Alexsandr0x how do i disable this partial html? Any config I can use?
