### ISSUE TITLE
Setting socialLinks title to "RSS" makes it disappear

### ISSUE THREAD

**Issue by twiclo** [joeroe/risotto#45]
This shows just fine on the my sidebar on the right
```
[[params.socialLinks]]
icon = "fa-solid fa-rss"
title = "rss"
url = "/rss"
```
however capitalizing the title makes it disappear
```
[[params.socialLinks]]
icon = "fa-solid fa-rss"
title = "RSS"
url = "/rss"
```

I've even tried other all caps 3 letter combos like "ABC". What's going on here?
Thanks for the theme btw. Very thorough

**Comment by joeroe** [comment]
I was previously able to reproduce this, but as of hugo v0.116.1 both `title: "rss"` and `title: "RSS"` seem to work fine, so presumably this was something upstream that has been fixed.
