### ISSUE TITLE
Firefox ignores the space after the asterisk in the ul li::marker rule

### ISSUE THREAD

**Issue by joeroe** [joeroe/risotto#5]
The issue appears to be with how Firefox handles UL/LI indentation compared to Chrome.

_Originally posted by @mntn-xyz in https://github.com/joeroe/risotto/issues/3#issuecomment-887933920_

**Comment by mntn-xyz** [comment]
I think this will fix it, but I haven't tested it yet.

```
/* Replace existing rule (strip space after asterisk) */
ul li::marker {
    content: '∗';
    color: var(--bright-bg);
}

/* Specify use of margin */
.page__body ul, .page__aside ul {
    margin-left: 0.75rem;
    padding-left: 0;
}
```

I noticed that this was fixed on sslarch.github.io, but without the .page_body and .page_aside selectors. This adds a space after the ./ in the header menu.

**Comment by mntn-xyz** [comment]
Fixed - confirmed
