### ISSUE TITLE
Highlight active heading in table of contents

### ISSUE THREAD

**Issue by kogutich** [joeroe/risotto#67]
Do you have any plans to add colour highlighting of the active heading in table of contents?
It would be great to have this feature and dynamically update when scrolling.
I attached an image how it may look (but it is just an example).

PS: great theme, love the minimalistic design
![Снимок экрана от 2024-03-27 20-09-45](https://github.com/joeroe/risotto/assets/6692799/cecf45cb-5630-4403-8be1-3e665d0d8b5f)

**Comment by joeroe** [comment]
Thank you for the suggestion. It would be a nice touch, but I don't think it would be possible to add without Javascript. The theme currently doesn't use any JS and I don't think it's worth changing that for a non-essential feature.
