### ISSUE TITLE
Pages in nested content directories missing from taxonomy list

### ISSUE THREAD

**Issue by saurabh-sm** [joeroe/risotto#78]
I have a couple of regular (non `_index.md)` pages tagged as `foo`. 

On navigating to `localhost:1313/tags/` I can see `foo` listed. 

When I click on it, I don't see any of the pages which have been tagged as `foo`, all I can see is the title `# Foo` at the top.

**Comment by joeroe** [comment]
Could you please give a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of this problem? Tag index pages should use the default list layout, which does list pages. On the example site this works, for example: <https://risotto.joeroe.io/tags/markdown/>

**Comment by saurabh-sm** [comment]
My website's layout looks like:

```
./content
├── dir-1
│   ├── file-1.md
│   ├── file-2.md
│   └── _index.md
├── dir-2
│   ├── file-3.md
│   ├── file-4.md
│   └── _index.md
├── _index.md
└── dir-3
    ├── dir-4
    │   ├── file-5.md
    │   └── file-6.md
    ├── dir-4.md
    ├── dir-5
    │   ├── file-7.md
    │   └── file-8.md
    ├── dir-5.md
    └── _index.md
```

There is a tag `foo` in files `file-6.md` and `file-8.md`. On navigating to `localhost:1313/tags`, I can see the tag `foo` listed. When I click on it, the page `http://localhost:1313/tags/foo/` is empty and doesn't list anything. 

Is there a way I can make sure that pages `file-6` and `file-8` are listed when I navigate to `http://localhost:1313/tags/foo/` ?

**Comment by joeroe** [comment]
So it seems the problem is with tags in nested sections, rather than tags in general? I'll investigate further.

**Comment by saurabh-sm** [comment]
Yes, the problem is only with nested content directories.

Thanks for looking into it.

**Comment by saurabh-sm** [comment]
Hi @joeroe - I more thing I want to point out about tagging nested content (please let me know if this this should be filed as a different bug):

All files in `dir-3` have a lot of textual content. Files like `file-6.md` and `file-8.md` have `## Some Heading` below the header. On navigating to `http;//localhost:1313/dir-3`, I can see the heading and contents of `file-6.md` and `file-8.md` listed below `_index.md`, `dir-4.md`, and `dir-5.md`.

When I add the `<!--more-->` before `## Some Heading` like:

```
Some text
<!--more-->

## Some Heading
...
...
```

The headings of `file-6.md` and `file-8.md` remain and content is replaced by the text above `<!--more-->`. 

I think neither of these things should be happening.

To mitigate this behavior, I have to add 

```
[_build]
  list = "never"
```

in the header of these files. This in-turn maybe causing nested tagged pages to not be listed, as I explained in my previous post.

**Comment by joeroe** [comment]
Yes, that will be why they don't show up in the list views.

risotto's list layouts don't include page content or summaries. It sounds like the pages in that section are using a different list layout – perhaps Hugo's default? Or one you have placed in your site's `layouts` directory? Could I ask you to again start a new site and try to make a minimal reproducible example of this problem with content/summaries in lists, so we can rule out that something in your site's config is causing this behaviour?

**Comment by saurabh-sm** [comment]
> risotto's list layouts don't include page content or summaries. 

It seems that in a nested structure, page content / summaries are included.

> It sounds like the pages in that section are using a different list layout – perhaps Hugo's default? Or one you have placed in your site's layouts/ directory? Could I ask you to again start a new site and try to make a minimal reproducible example of this problem with content/summaries in lists, so we can rule out that something in your site's config is causing this behaviour? 

The `layouts/` directory only has `robots.txt`. 

Each page in `dir-3` has the following content at the top:

```
+++
title = 'Some Webpage'
date = 2024-04-21T08:58:09-07:00
author = 'John Doe'
tags = ["foo"]
toc = true
[_build]
  list = "never"
+++
```

and the `_index.md` in this directory looks like:

```
+++
title = 'Directory 3'
type = "post"
+++

Some content
...
...
```

> Does it only happen within nested sections?

Yes

**Comment by saurabh-sm** [comment]
I got around the issue by:

+ Removing the below from non `_index.md` file:

  ```
  [_build]
    list = "never"
  ```

+ Removing `type = "post"` from all `dir`s

+ Renaming `dir.md` files to `_index.md` and moving them to their respective `dir/`s
