### ISSUE TITLE
change font

### ISSUE THREAD

**Issue by frankenstein91** [joeroe/risotto#80]
Is there an easy way to change the font?
I have some readers on my website with dyslexia. I would like to help them with the font https://github.com/antijingoist/opendyslexic

**Comment by joeroe** [comment]
Yes just set the font using CSS in the usual way. The theme only uses one font family, defined in `https://github.com/joeroe/risotto/blob/main/static/css/typography.css`, so you could e.g. override the variable `--font-monospace` or re-set the font family of `body` or any descendent element,
