### ISSUE TITLE
socialLinks param build errors

### ISSUE THREAD

**Issue by shabby-goddess** [joeroe/risotto#81]
love this hugo theme!

when i add two [params.socialLinks] sections to my hugo.toml (_a la_ [example site](https://github.com/joeroe/risotto/blob/main/exampleSite/config.toml)), hugo returns the following error: 

`Error: command error: failed to load config: "~/$SITE/hugo.toml:1:1": unmarshal failed: toml: table socialLinks already exists`

to make matters even more confusing, when i eliminate the second socialLinks param field in hugo.toml, running `hugo server` returns the following error for 'term', 'taxonomy', and 'page': 

`ERROR render of "term" failed: "/~/$SITE/themes/risotto/layouts/_default/baseof.html:21:24": execute of template failed: template: _default/list.html:21:24: executing "_default/list.html" at <partial "about.html" .>: error calling partial: "/~/$SITE/themes/risotto/layouts/partials/about.html:12:25": execute of template failed: template: partials/about.html:12:25: executing "partials/about.html" at <$item.url>: can't evaluate field url in type interface {}`

any ideas how to get the socialLinks param to start working? thanks lots !!

**Comment by shabby-goddess** [comment]
fixed: as it happens, i had added `[params.socialLinks]' to my hugo config, not `[[params.socialLinks]]`. can anyone explain why some `[params]` are enclosed with single brackets, and others in double brackets?

**Comment by shabby-goddess** [comment]
fixed: as it happens, i had added `[params.socialLinks]' to my hugo config, not `[[params.socialLinks]]`. can anyone explain why some `[params]` are enclosed with single brackets, and others in double brackets?

**Comment by joeroe** [comment]
Double brackets in TOML indicate an array of tables: https://toml.io/en/v1.0.0#array-of-tables
