### ISSUE TITLE
Showing recent posts on Home page

### ISSUE THREAD

**Issue by KrishnanN27** [joeroe/risotto#86]
Hi, am trying to find a way to show my recent posts , maybe with a limit to my Homepage, is it doable!

**Comment by joeroe** [comment]
Hi @KrishnanN27. Yes, Hugo supports doing this. There are no specific considerations for this theme, and you should be able to find plenty of how-tos online.

**Comment by KrishnanN27** [comment]
Thanks @joeroe , thats great news!
